B-08210 | User_Profile_Management_MM
Jyaheza/t4-project1-frontend pull request #21
Opened 2024-06-11 02:27 UTC by mmendiolajr

Added a user profile page that displays the users information such as name, email, and account id. Cypress IO tests have also been added for testing purposes. The CypressIO tests logs into one account, displays the information, and logs out into another account to display another user's information.

2024-06-11 13:17 UTC, markyd-XXI commented on src/components/MenuBar.vue
> +const userURL = "http://localhost:8081/profile";
Rather than hard-coding this url, create a route for the profile in router.js.

2024-06-11 13:18 UTC, markyd-XXI commented on src/components/MenuBar.vue
> +              <v-btn rounded variant="text" @click="redirectToLink(userURL)"> Profile </v-btn>
One you have a router for the profile page created, you can remove the redirectTotLink function and just call something like
```
router.push({name: "profile" });
```

2024-06-11 13:22 UTC, markyd-XXI requested changes
@mmendiolajr, I have just one change I am requesting.

2024-06-11 23:55 UTC, merged

2024-06-12 11:30 UTC, n-grounds commented on cypress/e2e/spec.cy.js
> +    cy.pause()
is there anything that can be validated on the Profile page?  even just that a name of the user is visible?